//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BathComplex.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentPricing
    {
        public int PricingID { get; set; }
        public int ApartmentID { get; set; }
        public string DayType { get; set; }
        public decimal PricePerHour { get; set; }
    
        public virtual Apartments Apartments { get; set; }
    }
}
