//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BathComplex.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentStatusLog
    {
        public int LogID { get; set; }
        public int ApartmentID { get; set; }
        public int StatusID { get; set; }
        public int SetByUserID { get; set; }
        public Nullable<System.DateTime> SetTime { get; set; }
        public string Notes { get; set; }
    
        public virtual Apartments Apartments { get; set; }
        public virtual ApartmentStatuses ApartmentStatuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
