//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BathComplex.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingServices
    {
        public int BookingServiceID { get; set; }
        public int BookingID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public decimal PricePerUnit { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Services Services { get; set; }
    }
}
