//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BathComplex.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int ExpenseID { get; set; }
        public string Description { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int CreatedByUserID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual ExpenseCategories ExpenseCategories { get; set; }
        public virtual Users Users { get; set; }
    }
}
