//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BathComplex.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BathComplexDBEntities : DbContext
    {
        public BathComplexDBEntities()
            : base("name=BathComplexDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApartmentPricing> ApartmentPricing { get; set; }
        public virtual DbSet<Apartments> Apartments { get; set; }
        public virtual DbSet<ApartmentStatuses> ApartmentStatuses { get; set; }
        public virtual DbSet<ApartmentStatusLog> ApartmentStatusLog { get; set; }
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<BookingServices> BookingServices { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ExpenseCategories> ExpenseCategories { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<ServiceCategories> ServiceCategories { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<V_DailyFinanceSummary> V_DailyFinanceSummary { get; set; }
        public virtual DbSet<V_ExpensesByDay> V_ExpensesByDay { get; set; }
    }
}
