//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BathComplex.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DailyFinanceSummary
    {
        public Nullable<System.DateTime> Date { get; set; }
        public decimal Income { get; set; }
        public decimal Expenses { get; set; }
        public Nullable<decimal> Profit { get; set; }
    }
}
