//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BathComplex.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ExpensesByDay
    {
        public System.DateTime ExpenseDate { get; set; }
        public Nullable<decimal> TotalExpenses { get; set; }
    }
}
